[package]
name = "chip-8"
version = "0.1.0"
authors = ["Michael Kohl <me@citizen428.net>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0"
sdl2 = "0.37.0"
